server:
  port: 8086
  servlet:
    context-path: /api/questions

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/question_service"
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      persistence:
        query:
          timeout: 120000
      hibernate:
        jdbc:
          batch_size: 500
        order_updates: true
        order_inserts: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: question-service
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.trusted.packages: "*"

app:
  services:
    classrooms: http://localhost:8084/api/classrooms
    exam: http://localhost:8088/api/exam